Upgrade to Solr 8.8
codice/ddf pull request #6526
Opened 2021-03-01 19:58 UTC by frnkshin

#### What does this PR do?
Upgrades to Solr 8.8

#### Who is reviewing it? 

@jMoneee
@shaundmorris
@abel-connexta
@kentmorrissey
@lavoywj
@frnkshin

#### Select relevant component teams: 
@codice/solr 

#### Ask 2 committers to review/merge the PR and tag them here.
@pklinef
@lambeaux

#### How should this be tested?

```
1.  Run SolrCloud docker image as directed by https://github.com/codice/ddf/blob/master/distribution/docker/solrcloud/README.md
2. Verify version by going into Solr admin console
3. Index data and verify search works
```

#### Any background context you want to provide?
Upgrade Solr to 8.8
https://lucene.apache.org/solr/8_8_0/changes/Changes.html

#### What are the relevant tickets?
Fixes: #n/a

#### Screenshots

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

2021-03-01 19:59 UTC, frnkshin commented
build now

2021-03-01 23:33 UTC, pklinef requested changes

2021-03-01 23:33 UTC, pklinef commented on pom.xml
> +        <solr.version>8.8.0</solr.version>
Solr 8.8.1 just recently released with 5 bug fixes.

https://lucene.apache.org/solr/news.html#apache-solrtm-881-available

2021-03-02 18:14 UTC, frnkshin commented
build now

2021-03-02 21:28 UTC, shaundmorris approved these changes

2021-03-02 21:43 UTC, frnkshin commented
build now

2021-03-03 15:51 UTC, frnkshin commented
build now

2021-03-03 21:00 UTC, shaundmorris approved these changes
Do we need to specific Solr cloud tests as well?

2021-03-08 19:26 UTC, lavoywj approved these changes

2021-03-08 20:00 UTC, pklinef commented
Solr 8.8.1 has moved to Commons IO 2.8.0.

https://github.com/codice/ddf/blob/7dac6e1c4b78a3f156b30c964c9bac24b4d86939/platform/solr/solr-dependencies/pom.xml#L73-L77

2021-03-15 15:35 UTC, AzGoalie approved these changes

2021-03-16 18:26 UTC, frnkshin commented
build now

2021-03-17 14:56 UTC, pklinef approved these changes

2021-03-17 14:56 UTC, merged