Upgrade to Karaf 4.3.4
codice/ddf pull request #6662
Opened 2021-12-13 18:00 UTC by pklinef

#### What does this PR do?
Upgrades to Karaf 4.3.4. 

This upgrades Pax Logging which resolves Log4j CVE CVE-2021-44228 without configuration changes. Log4j configuration can be used to mitigate this CVE without this upgrade.

https://blog.cloudflare.com/inside-the-log4j2-vulnerability-cve-2021-44228/

#### Who is reviewing it? 

#### Select relevant component teams: 

@codice/security

#### Ask 2 committers to review/merge the PR and tag them here.

#### How should this be tested?

Unzip, run, ingest data, and search.

#### Any background context you want to provide?

#### What are the relevant tickets?
Fixes: n/a

#### Screenshots

#### Checklist:
- [ n/a ] Documentation Updated
- [ n/a ] Update / Add Threat Dragon models
- [ n/a ] Update / Add Unit Tests
- [ n/a ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

2021-12-13 18:50 UTC, pklinef commented
The Karaf 4.3.4 vote is in progress currently and will be open for 72 hours.

https://mail-archives.apache.org/mod_mbox/karaf-dev/202112.mbox/%3Cb4ec37ab-bfe5-a2d0-bcdb-69e7864fcce6%40nanthrax.net%3E

2021-12-16 21:16 UTC, ryeats approved these changes

2021-12-16 21:19 UTC, LinkMJB approved these changes

2021-12-16 21:19 UTC, LinkMJB commented on pom.xml
> +        <solr.log4j.version>2.16.0</solr.log4j.version>
Good call going to 2.16.0 instead of 2.15.0. HOWEVER, I saw an article that even 2.16.0 has a vulnerability that they are not demonstrating exploitation for yet, with anticipation for yet ANOTHER release: https://thehackernews.com/2021/12/hackers-begin-exploiting-second-log4j.html

2021-12-16 21:19 UTC, LinkMJB commented on pom.xml
> +        <apache-log4j.version>2.16.0</apache-log4j.version>
Good call going to 2.16.0 instead of 2.15.0. HOWEVER, I saw an article that even 2.16.0 has a vulnerability that they are not demonstrating exploitation for yet, with anticipation for yet ANOTHER release: https://thehackernews.com/2021/12/hackers-begin-exploiting-second-log4j.html

2021-12-16 21:24 UTC, bakejeyner approved these changes

2021-12-18 18:21 UTC, pklinef commented
build now

2021-12-21 15:43 UTC, LinkMJB requested changes

2021-12-21 15:43 UTC, LinkMJB commented on pom.xml
> +        <apache-log4j.version>2.16.0</apache-log4j.version>
Now 2.17.0 is out

2021-12-21 15:43 UTC, LinkMJB commented on pom.xml
> +        <solr.log4j.version>2.16.0</solr.log4j.version>
Now 2.17.0 is out

2021-12-29 15:34 UTC, LinkMJB commented on pom.xml
> +        <apache-log4j.version>2.16.0</apache-log4j.version>
log4j up to 2.17.1 now due to all of the vulnerabilities people are uncovering 🤦 https://thehackernews.com/2021/12/new-apache-log4j-update-released-to.html

2021-12-29 15:35 UTC, LinkMJB commented on pom.xml
> +        <solr.log4j.version>2.16.0</solr.log4j.version>
log4j up to 2.17.1 now due to all of the vulnerabilities people are uncovering 🤦 https://thehackernews.com/2021/12/new-apache-log4j-update-released-to.html

2022-01-04 16:30 UTC, pklinef commented
build now

2022-01-04 18:03 UTC, pklinef commented
build now

2022-01-04 19:55 UTC, pklinef commented
build now

2022-01-04 23:14 UTC, pklinef commented
build now

2022-01-05 17:14 UTC, pklinef commented on pom.xml
> +        <apache-log4j.version>2.16.0</apache-log4j.version>
Thankfully the later CVEs have much lower scores. I don't think Karaf or Pax Logging are planning any near term releases for the newer versions of Log4j.

2022-01-05 18:27 UTC, merged