Example on how to patch Log4Shell CVE-2021-44228
codice/ddf pull request #6663
Opened 2021-12-13 23:24 UTC by LinkMJB

#### What does this PR do?
Patches Apache log4j2 against CVE-2021-44228

#### Who is reviewing it? 
@shaundmorris 
@stustison 

#### Select relevant component teams: 
@codice/security 
@codice/solr 

#### Ask 2 committers to review/merge the PR and tag them here.
If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
(please choose ONLY two committers from below)
@shaundmorris
@stustison

#### Any background context you want to provide?
See: https://www.lunasec.io/docs/blog/log4j-zero-day/

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

2021-12-13 23:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/codice/ddf?pullRequest=6663) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/codice/ddf?pullRequest=6663) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/codice/ddf?pullRequest=6663) it.</sub>

2021-12-13 23:27 UTC, LinkMJB commented
build now

2021-12-14 15:15 UTC, ricklarsen approved these changes

2021-12-14 18:45 UTC, pklinef commented
I do not think this will actual fix DDF since log4j is pulled in through Pax Logging which these changes do not address.

2021-12-14 21:53 UTC, LinkMJB commented
build now

2021-12-14 22:00 UTC, LinkMJB commented
> I do not think this will actual fix DDF since log4j is pulled in through Pax Logging which these changes do not address.

@pklinef what's the effect of having log4j defined in our project pom.xml and built, if we don't utilize it? It does seem like we are at least using a vulnerable version of log4j for capturing logging from solr:
```
[2021-12-13T23:31:58.377Z] [INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ solr-logging ---
[2021-12-13T23:31:58.377Z] [WARNING] JAR will be empty - no content was marked for inclusion!
16:31:58  [INFO] Building jar: /jenkins/workspace/DDF/PR-6663/1/platform/solr/solr-logging/target/solr-logging-2.28.0-SNAPSHOT.jar
16:31:58  [INFO] 
[2021-12-13T23:31:58.377Z] [INFO] --- maven-shade-plugin:2.4.3:shade (default) @ solr-logging ---
16:31:58  [INFO] Excluding org.slf4j:slf4j-api:jar:1.7.32 from the shaded jar.
16:31:58  [INFO] Including org.slf4j:slf4j-log4j12:jar:1.7.32 in the shaded jar.
16:31:58  [INFO] Including log4j:log4j:jar:1.2.17 in the shaded jar.
16:31:58  [INFO] Including org.slf4j:jul-to-slf4j:jar:1.7.24 in the shaded jar.
16:31:58  [INFO] Including org.slf4j:jcl-over-slf4j:jar:1.7.32 in the shaded jar.
16:31:58  [INFO] Including org.apache.logging.log4j:log4j-1.2-api:jar:2.15.0 in the shaded jar.
16:31:58  [INFO] Including org.apache.logging.log4j:log4j-api:jar:2.15.0 in the shaded jar.
16:31:58  [INFO] Including org.apache.logging.log4j:log4j-core:jar:2.15.0 in the shaded jar.
16:31:58  [INFO] Including org.apache.logging.log4j:log4j-slf4j-impl:jar:2.15.0 in the shaded jar.
[2021-12-13T23:31:58.952Z] [WARNING] log4j-1.2.17.jar, log4j-1.2-api-2.15.0.jar define 44 overlapping classes: 
[2021-12-13T23:31:58.952Z] [WARNING]   - org.apache.log4j.helpers.AppenderAttachableImpl
[2021-12-13T23:31:58.952Z] [WARNING]   - org.apache.log4j.spi.OptionHandler
[2021-12-13T23:31:58.952Z] [WARNING]   - org.apache.log4j.or.ObjectRenderer
[2021-12-13T23:31:58.952Z] [WARNING]   - org.apache.log4j.rewrite.PropertyRewritePolicy
[2021-12-13T23:31:58.952Z] [WARNING]   - org.apache.log4j.spi.LoggerRepository
[2021-12-13T23:31:58.952Z] [WARNING]   - org.apache.log4j.NDC
[2021-12-13T23:31:58.952Z] [WARNING]   - org.apache.log4j.PatternLayout
[2021-12-13T23:31:58.953Z] [WARNING]   - org.apache.log4j.LogManager
[2021-12-13T23:31:58.953Z] [WARNING]   - org.apache.log4j.BasicConfigurator
[2021-12-13T23:31:58.953Z] [WARNING]   - org.apache.log4j.spi.ErrorHandler
[2021-12-13T23:31:58.953Z] [WARNING]   - 34 more...
[2021-12-13T23:31:58.953Z] [WARNING] log4j-slf4j-impl-2.15.0.jar, slf4j-log4j12-1.7.32.jar define 3 overlapping classes: 
[2021-12-13T23:31:58.953Z] [WARNING]   - org.slf4j.impl.StaticMarkerBinder
[2021-12-13T23:31:58.953Z] [WARNING]   - org.slf4j.impl.StaticLoggerBinder
[2021-12-13T23:31:58.953Z] [WARNING]   - org.slf4j.impl.StaticMDCBinder
[2021-12-13T23:31:58.953Z] [WARNING] maven-shade-plugin has detected that some class files are
[2021-12-13T23:31:58.953Z] [WARNING] present in two or more JARs. When this happens, only one
[2021-12-13T23:31:58.953Z] [WARNING] single version of the class is copied to the uber jar.
[2021-12-13T23:31:58.953Z] [WARNING] Usually this is not harmful and you can skip these warnings,
[2021-12-13T23:31:58.953Z] [WARNING] otherwise try to manually exclude artifacts based on
[2021-12-13T23:31:58.953Z] [WARNING] mvn dependency:tree -Ddetail=true and the above output.
[2021-12-13T23:31:58.953Z] [WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
```

2021-12-14 22:16 UTC, pklinef commented
@LinkMJB DDF does use an impacted version of Log4j through Pax Logging. 

https://github.com/ops4j/org.ops4j.pax.logging/issues/414

PR #6662 will upgrade to a version of Karaf that upgrades Pax Logging though that version of Karaf is not released yet (currently being voted on). Solr is also working on a 8.11.1 release to resolve their use of previous versions of Log4j.

https://solr.apache.org/security.html#apache-solr-affected-by-apache-log4j-cve-2021-44228

That `solr-logging` module which is embedded a bad version of Log4j is used in test classes only. It is not included in the final distribution zip. The `apache-log4j.version` is used to figure out which version of the Log4j API to compile against. But the actual Log4j implementation and APIs provided in DDF at runtime are controlled by Pax Logging. And the Log4j version used by Solr in newer versions of DDF are controlled by the Solr docker images which have been patched.

All of that said, these version numbers should be bumped to up to avoid false positive CVE scans and to match the Pax Logging version of Log4j. I just wanted to make it clear that this PR alone will not protect DDF from the CVE as it is. I did miss these maven properties so this is still a very helpful PR.

2021-12-14 22:46 UTC, pklinef requested changes
Here is another one. That comment looks out of date. Also it is very easy to miss that variable when doing a Karaf/Pax Logging upgrade. Hopefully we can just remove this. But if not, then at least we should try to pull it up to the top level parent pom for visibility.

https://github.com/codice/ddf/blob/ddf-2.27.1/platform/security/platform-security-core-api/pom.xml#L28-L29

2021-12-16 21:11 UTC, pklinef commented
I added your changes to #6662 which upgrades Pax Logging and Log4j through Karaf. Your changes should have been in that PR but I forgot about those other log4j versions in the system. That PR is still waiting for the Karaf vote to close and that version to release.

2021-12-16 21:14 UTC, LinkMJB commented
> I added your changes to #6662 which upgrades Pax Logging and Log4j through Karaf. Your changes should have been in that PR but I forgot about those other log4j versions in the system. That PR is still waiting for the Karaf vote to close and that version to release.

Thanks @pklinef! I'll close this PR, I appreciate you working on this!!! Glad to have a knowledgeable professional software engineer that has experience maintaining the DDF code-base, handling this instead of me pretending to know what I am doing 😄 🤡

2021-12-16 21:14 UTC, closed without merging